import { Trans } from '@lingui/react/macro';

import { Button, Column, Img, Section, Text } from '../components';
import { TemplateDocumentImage } from './template-document-image';

export type TemplateDocumentCompletedVariant = 'standard' | 'ua-kep-pades' | 'ua-kep-evidence';

export type TemplateDocumentCompletedProps = {
  downloadLink: string;
  documentName: string;
  assetBaseUrl: string;
  customBody?: string;
  completedVariant?: TemplateDocumentCompletedVariant;
};

export const TemplateDocumentCompleted = ({
  downloadLink,
  documentName,
  assetBaseUrl,
  customBody,
  completedVariant = 'standard',
}: TemplateDocumentCompletedProps) => {
  const getAssetUrl = (path: string) => {
    return new URL(path, assetBaseUrl).toString();
  };

  const isUaKepPades = completedVariant === 'ua-kep-pades';
  const isUaKepEvidence = completedVariant === 'ua-kep-evidence';

  return (
    <>
      <TemplateDocumentImage className="mt-6" assetBaseUrl={assetBaseUrl} />

      <Section>
        <Section className="mb-4">
          <Column align="center">
            <Text className="font-semibold text-base text-foreground">
              <Img
                src={getAssetUrl('/static/completed.png')}
                className="-mt-0.5 mr-2 inline h-7 w-7 align-middle"
                alt=""
              />
              <Trans>Completed</Trans>
            </Text>
          </Column>
        </Section>

        <Text className="mb-0 text-center font-semibold text-foreground text-lg">
          {customBody || <Trans>“{documentName}” was signed by all signers</Trans>}
        </Text>

        <Text className="my-1 text-center text-base text-muted-foreground">
          {isUaKepPades ? (
            <Trans>The PAdES PDF generated by the КЕП/УЕП signing flow is attached to this email.</Trans>
          ) : isUaKepEvidence ? (
            <Trans>
              The КЕП/УЕП evidence package is available from the download page. A PAdES PDF is attached when the signing
              provider produces it.
            </Trans>
          ) : (
            <Trans>Continue by downloading the document.</Trans>
          )}
        </Text>

        <Section className="mt-8 mb-6 text-center">
          <Button
            className="rounded-lg border border-border border-solid px-4 py-2 text-center font-medium text-foreground text-sm no-underline"
            href={downloadLink}
          >
            <Img src={getAssetUrl('/static/download.png')} className="mr-2 mb-0.5 inline h-5 w-5 align-middle" alt="" />
            {isUaKepPades || isUaKepEvidence ? <Trans>Open downloads</Trans> : <Trans>Download</Trans>}
          </Button>
        </Section>
      </Section>
    </>
  );
};

export default TemplateDocumentCompleted;
